export { default as Footer } from './footer/Footer';
export { default as Stream } from './stream/Stream';
export { default as Header } from './header/Header';
export { default as Events } from './events/Events';
export { default as MovieDetails } from './movieDetails/MovieDetails';
export { default as Payment } from './payment/Payment';
export { default as NowShowing } from './nowShowing/NowShowing';
export { default as UpCommingMovies } from './upCommingMovies/UpCommingMovies';
export { default as ContactForm } from './contactForm/ContactForm';
export { default as CurrentLiveEvent } from './CurrentLiveEvent/CurrentLiveEvent';
export { default as LiveEventForm } from './LiveEventForm/LiveEventForm';
export { default as AddMovieManagement } from './movieManagement/AddMovieManagement';
export { default as ViewMovieManagement } from './movieManagement/ViewMovieManagement';
export { default as AdminContact } from './adminContactView/adminContactView';
export { default as AdminUpcomingMovies } from './AdminUpcomingMovies/AdminUpcomingMovies';
export { default as AdminEditUpcomingMovie } from './AdminUpcomingMovies/AdminEditUpcomingMovie.jsx';
export { default as MovieProfileManagement } from './movieManagement/MovieProfileManagement';
export { default as DashboardContainer } from './DashboardContainer/DashboardContainer';
export { default as LiveStreamManagement } from './LiveStreamManagement/LiveStreamManagement';
export { default as LiveEventPayment } from './payment/LiveEventPayment';
export { default as MoviePayment } from './payment/MoviePayment';
export { default as AdminUsersManagement } from './usersManagement/AdminUsersManagement';
export { default as AdminAddNewsManagement } from './adminAddNews/AdminAddNewsManagement';
export { default as Trailers } from './Trailers/Trailers';
export { default as MovieWatch} from './movieView/MovieWatch';
export { default as LiveWatchEvent} from './events/LiveWatchEvent';
export { default as LiveProfile } from './events/LiveProfile.jsx';
export { default as EditorAccountForm } from './AdminSetting/EditorAccountForm.jsx';
export { default as PasswordResetForm } from './AdminSetting/PasswordResetForm.jsx';
export { default as PhoneNumberForm } from './AdminSetting/PhoneNumberForm.jsx';
export { default as AdminEditNews } from './adminAddNews/AdminEditNews.jsx';
export { default as EventPayment } from './payment/EventPayment.jsx';
export { default as Paybuttons } from './payment/Paybuttons.jsx';

